name: blocs
description: The Business Logic Components for mira mira

environment:
  sdk: '>=2.0.0-dev.28.0 <3.0.0'

dependencies:
  middleware:
    path: ../middleware
  rxdart: 0.18.0

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
